### ISSUE TITLE
Make tests

### ISSUE THREAD

**Issue by kickingvegas** [kickingvegas/casual-calc#1]
Create test suite for Casual.

**Comment by raxod502** [comment]
One option that I've explored in the past, though not thoroughly enough to get something put together entirely, is to define a test runner function that takes a keyboard sequence, plays it back using the Emacs keyboard macro system, and then inspects the results of the buffer. That way you can have a list of test specs that are pretty concise, where each one exercises a different function, and easily run them all automatically.

See https://github.com/radian-software/dumbparens/blob/main/dumbparens-tests.el for an example.

**Comment by kickingvegas** [comment]
@raxod502 thanks for the input! Looks like `execute-kbd-macro` is my friend here. Saw this other post showing its use to test a Transient. https://emacs.stackexchange.com/questions/69534/acceptance-test-for-a-flow-that-uses-the-transient-package
