### ISSUE TITLE
Suggestion: Angle format; no need for dedicated menu

### ISSUE THREAD

**Issue by danielfleischer** [kickingvegas/casual-calc#142]
Have the `a` toggle between the 3 options (round robin), reduce a trivial menu. 

Thanks for the library!

**Comment by kickingvegas** [comment]
Thanks much for taking the time to offer this suggestion! That said, I think multi-state toggle controls are too much a power user feature and does so at the cost of discoverability which I consider a core value to Casual. Menus can make explicit what the options are (in this case the angle measure modes) as well as provide random access to an option. As such, I respectfully `wontfix` this issue. Regards - Charles.
