### ISSUE TITLE
Support `casual-lib-use-unicode` for math symbols in labels

### ISSUE THREAD

**Issue by TriAttack238** [kickingvegas/casual-calc#171]
Hello, 
I've gotten Casual-calc to work, but the menu seems to have trouble loading certain characters/symbols. Is there some sort of setting or dependency I'm missing?

![image](https://github.com/user-attachments/assets/a9916f0d-325b-45ff-9557-1efbe2b31b0d)

Platform: Windows 11, x86_64
Emacs: GNU Emacs 29.4 (build 2, x86_64-w64-mingw32) of 2024-06-23
Casual Calc Version: 1.11.0

**Comment by kickingvegas** [comment]
@TriAttack238 thanks for sharing this. I've made commentary on #170 that I believe is the same issue as the one you are seeing.

Going to use this issue to track an change/enhancement to optionally display math/Unicode symbols using the variable `casual-lib-use-unicode`.

**Comment by TriAttack238** [comment]
So the issue may lie with windows instead of EMacs? I never considered that. Thank you for the insight, I will try to investigate this matter.

**Comment by kickingvegas** [comment]
@TriAttack238 BTW, have you tried out the latest release with optional unicode support?

**Comment by TriAttack238** [comment]
Yes, this is what it looks like on my end:
![image](https://github.com/user-attachments/assets/f3343ca7-0c9a-4798-a617-f9c796f38d8c)

**Comment by kickingvegas** [comment]
@TriAttack238 If you get the math symbol support worked out on Windows, you can use it by turning on (u) Use Unicode Symbols in (m) Modes, Displays, Angles.
